# Generated by Django 2.2.6 on 2019-10-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0003_attendance_usercoords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
