# Generated by Django 2.2.6 on 2019-10-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0004_auto_20191031_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='ongeo.Organisation'),
        ),
    ]
