# Generated by Django 2.2.6 on 2019-11-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0008_allatendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='allatendees',
            name='f_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allatendees',
            name='l_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
