# Generated by Django 2.2.6 on 2019-11-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0009_auto_20191103_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCoords',
        ),
    ]
