# Generated by Django 2.2.6 on 2019-11-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0010_delete_usercoords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='organisation',
            new_name='community',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
