# Generated by Django 2.2.6 on 2019-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0011_auto_20191103_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allatendees',
            name='f_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='allatendees',
            name='l_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
