# Generated by Django 2.2.6 on 2019-11-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0012_auto_20191103_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allatendees',
            old_name='created_on',
            new_name='checked_in_on',
        ),
        migrations.RenameField(
            model_name='allatendees',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='allatendees',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
