# Generated by Django 2.2.6 on 2019-11-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0013_auto_20191103_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='allatendees',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
