# Generated by Django 2.2.6 on 2019-11-04 06:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0014_allatendees_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='members',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
