# Generated by Django 2.2.8 on 2020-01-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0015_auto_20191104_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allatendees',
            name='last_seen',
        ),
    ]
