# Generated by Django 4.2.30 on 2026-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0018_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
