# Generated by Codex on 2026-05-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ongeo', '0019_organisation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='organisation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checkpoints',
                to='ongeo.organisation',
            ),
        ),
    ]
